apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  creationTimestamp: null
  name: cicd-event-listener
  namespace: cicd
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: github-push-binding
    interceptors:
    - params:
      - name: secretRef
        value:
          secretKey: webhook-secret-key
          secretName: gitops-webhook-secret
      ref:
        name: github
    - params:
      - name: filter
        value: (header.match('X-GitHub-Event', 'push') && body.repository.full_name
          == 'stas-at-ibm/gitops-os-argocd-demo')
      - name: overlays
        value:
        - expression: body.ref.split('/')[2]
          key: ref
      ref:
        name: cel
    name: ci-dryrun-from-push
    template:
      ref: ci-dryrun-from-push-template
  - bindings:
    - ref: dev-app-taxi-os-argocd-demo-taxi-os-argocd-demo-binding
    - ref: github-push-binding
    interceptors:
    - params:
      - name: secretRef
        value:
          secretKey: webhook-secret-key
          secretName: webhook-secret-dev-taxi-os-argocd-demo
      ref:
        name: github
    - params:
      - name: filter
        value: (header.match('X-GitHub-Event', 'push') && body.repository.full_name
          == 'stas-at-ibm/taxi-os-argocd-demo')
      - name: overlays
        value:
        - expression: body.ref.split('/')[2]
          key: ref
      ref:
        name: cel
    name: app-ci-build-from-push-taxi-os-argocd-demo
    template:
      ref: app-ci-template
status:
  configuration:
    generatedName: ""
