apiVersion: v1
data:
  index.html: |+
    <!DOCTYPE html>
    <html>
    <head>
    <title>Dev Environment</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
    </style>
    </head>
    <body>
    <h1>Book Taxi - Dev Environment</h1>
    <p>This is the page content from the demo.</p>
    </body>
    </html>

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: www-files
  namespace: dev
