apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: taxi-os-argocd-demo
    app.kubernetes.io/part-of: app-taxi-os-argocd-demo
  name: taxi-os-argocd-demo
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: taxi-os-argocd-demo
      app.kubernetes.io/part-of: app-taxi-os-argocd-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: taxi-os-argocd-demo
        app.kubernetes.io/part-of: app-taxi-os-argocd-demo
    spec:
      containers:
        - image: quay.io/repository/stanislavibm/taxi:623e8c43c9e0d57843aa4917fccc1ec9de3a9c8f
          imagePullPolicy: Always
          name: taxi-os-argocd-demo
          volumeMounts:
            - name: web-files
              mountPath: /usr/share/booktaxi
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
      volumes:
        - name: web-files
          configMap:
            name: www-files
          resources: {}
      serviceAccountName: default
status: {}
